### ISSUE TITLE
Mailer-errors while adding/editing FAQ's using Redmine trunk r2700

### ISSUE THREAD

**Issue by MischaTheEvil** [zouchaoqun/ezfaq#1]
While saving a new/edited FAQ-item I receive the following error using EzFAQ 0.3.4:

<pre>
Processing EzfaqController#new (for 192.168.1.2 at 2009-05-06 18:26:31) [POST]
  Parameters: {"faq"=>{"related_message_id"=>"", "answer"=>"Answer 1", "related_version_id"=>"", "category_id"=>"1", "question"=>"FAQ 1", "assigned_to_id"=>"", "due_date"=>"2009-05-07", "difficulty"=>"5", "related_issue_id"=>""}, "commit"=>"Create", "action"=>"new", "id"=>"test", "controller"=>"ezfaq", "attachments"=>{"1"=>{"description"=>"", "file"=>""}}, "difficulty_label"=>"Difficluty"}

ActionView::TemplateError (Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id) on line #1 of vendor/plugins/ezfaq_plugin/app/views/faq_mailer/faq_add.text.plain.rhtml:
1: <%= l(:text_faq_added, :title => "##{@faq.id}", :author => @faq.author) %>
2: 
3: ----------------------------------------
4: <%= render :partial => "faq_text_plain", :locals => { :faq => @faq, :faq_url => @faq_url } %>

    /path/to/redmine/vendor/plugins/ezfaq_plugin/app/views/faq_mailer/faq_add.text.plain.rhtml:1
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/renderable.rb:39:in `send'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/renderable.rb:39:in `render'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/template.rb:73:in `render_template'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/base.rb:256:in `render'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:564:in `render'
    /path/to/redmine/app/models/mailer.rb:300:in `render_message'
    /path/to/redmine/vendor/plugins/ezfaq_plugin/app/models/faq_mailer.rb:37:in `faq_add'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/part_container.rb:28:in `part'
    /path/to/redmine/vendor/plugins/ezfaq_plugin/app/models/faq_mailer.rb:36:in `faq_add'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:462:in `__send__'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:462:in `create!'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:455:in `initialize'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:392:in `new'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:392:in `method_missing'
    /path/to/redmine/vendor/plugins/ezfaq_plugin/app/controllers/ezfaq_controller.rb:79:in `new'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in `send'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in `perform_action_without_filters'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:617:in `call_filters'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/1.8/benchmark.rb:293:in `measure'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/rescue.rb:136:in `perform_action_without_caching'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/caching/sql_cache.rb:13:in `passenger_orig_perform_action'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/query_cache.rb:8:in `cache'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/caching/sql_cache.rb:12:in `passenger_orig_perform_action'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/request_handler.rb:53:in `perform_action'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:524:in `send'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:524:in `process_without_filters'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:606:in `process_without_session_management_support'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/session_management.rb:134:in `process'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:392:in `process'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:183:in `handle_request'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:110:in `dispatch_unlocked'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:123:in `dispatch'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:122:in `synchronize'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:122:in `dispatch'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:132:in `dispatch_cgi'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:39:in `dispatch'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/request_handler.rb:38:in `process_request'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_request_handler.rb:163:in `main_loop'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/application_spawner.rb:307:in `start_request_handler'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/application_spawner.rb:276:in `handle_spawn_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/utils.rb:165:in `safe_fork'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/utils.rb:163:in `fork'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/utils.rb:163:in `safe_fork'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/application_spawner.rb:274:in `handle_spawn_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/utils.rb:165:in `safe_fork'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/utils.rb:163:in `fork'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/utils.rb:163:in `safe_fork'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/application_spawner.rb:273:in `handle_spawn_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:317:in `__send__'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:317:in `main_loop'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:168:in `start_synchronously'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:135:in `start'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:112:in `fork'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:112:in `start'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/application_spawner.rb:177:in `start'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/framework_spawner.rb:270:in `handle_spawn_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/framework_spawner.rb:263:in `synchronize'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/framework_spawner.rb:263:in `handle_spawn_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:317:in `__send__'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:317:in `main_loop'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:168:in `start_synchronously'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:135:in `start'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:112:in `fork'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:112:in `start'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/railz/framework_spawner.rb:87:in `start'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/spawn_manager.rb:218:in `spawn_rails_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/spawn_manager.rb:213:in `synchronize'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/spawn_manager.rb:213:in `spawn_rails_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/spawn_manager.rb:122:in `spawn_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/spawn_manager.rb:247:in `handle_spawn_application'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:317:in `__send__'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:317:in `main_loop'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/lib/passenger/abstract_server.rb:168:in `start_synchronously'
    /opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/passenger-2.0.3/bin/passenger-spawn-server:46

Rendering ./public/500.html (500 Internal Server Error)

</pre>

My environment:
- Redmine trunk @ r2700
- Apache 2.x, Phusion Passenger 2.0.3, Rails 2.2.2, Ruby Enterprise Edition 1.8.6-x
- MySQL 4.1.20

**Comment by zouchaoqun** [comment]
Hi,  MischaTheEvil 
I don't check issues here, so I haven't see this issue.
I updated to the newest trunk of redmine weekly, too. And I haven't see this error.
Can you try it with the lastest redmine trunk and to see if the error still there?

**Comment by MischaTheEvil** [comment]
Hello Zou Chaoqun,

Thanks for your reply. Maybe it's better to disable the (issue tracking) facilities here on GitHub (presuming that it's possible here on GitHub -I'm not a big fan of GitHub (yet)-) when they are not used and/or monitored.

Regarding the issue I've reported; I've just taken a renewed look at it using a clean Redmine trunk at r2783 with the EzFAQ plugin at SHA: e13de183bfa2d4c3a2780ee61d4a1990a00ea8cf and noticed that the issue was still persisting.

Now I took a closer look at the issue (checked the behaviour of FAQ-updates in contrast to the behaviour of FAQ-additions, within the code) and think I've found the cause of it.

The defect seems to reside in the `faq_add`-method in the `faq_mailer`-model; the following two lines contains the error:
- http://github.com/zouchaoqun/ezfaq/blob/e13de183bfa2d4c3a2780ee61d4a1990a00ea8cf/app/models/faq_mailer.rb#L37
- http://github.com/zouchaoqun/ezfaq/blob/e13de183bfa2d4c3a2780ee61d4a1990a00ea8cf/app/models/faq_mailer.rb#L41

As visible in the `faq_update`-method the body isn't passed correctly by the `render_message`-method at both lines. I've changed both method-calls to look like the following:

<pre>p.body = render_message("faq_add.text.***.rhtml", body)</pre>


After this modification I'm able to add and update FAQ's without suffering the error (before the modification the FAQ's were actually saved in the DB befóre the error kicked-in).

HTH.. ;) Btw: where do you want future issues/comments regarding the plugin (and your other ones) to go to? Redmine.org forums?

PS: I hope that GitHub understands my GFM-interpretation... :smirk:

Kind regards,

Mischa.

**Comment by zouchaoqun** [comment]
Yes, you are right. It is a defect. I have corrected it in version 0.3.5. Thanks!
Please report bugs at github or at redmine.org, I will try to check them some times. You can send a mail to zouchaoqun@gmail.com, too, I check that mail accout more ofen.
