### ISSUE TITLE
Problem with SQLite3

### ISSUE THREAD

**Issue by haru** [zouchaoqun/ezfaq#2]
Hi.
ezFAQ is a nice plugin. Thanks for your work.

By the way, I got a problem. This plugin does not works with SQLite3.
Following error was happend.

<pre>
ActiveRecord::StatementInvalid in EzfaqController#index

SQLite3::SQLException: no such column: true: SELECT * FROM "faqs" WHERE (project_id = 1 and category_id is not null and is_valid = true) 
</pre>

This error happens because SQLite's boolean value is '1' or '0', not a 'true' or 'false'.

Change the code from

<pre>
:condtions => 'is_valid = true'
</pre>

to

<pre>
:contditions => ['is_valid = ?', true]
</pre>

Then it will be works.

I changed your code like below.
In ezfaq_controller.rb, line 34, 35.

<pre>
@categorized_faqs = Faq.find(:all, :conditions => ["project_id = #{@project.id} and category_id is not null and is_valid = ?", true])
@not_categorized_faqs = Faq.find(:all, :conditions => ["project_id = #{@project.id} and category_id is null and is_valid = ?", true], :order => "question")
</pre>

line 47.

<pre>
@invalid_faqs = Faq.find(:all, :conditions => ["project_id = #{@project.id} and is_valid = ?", false], :order => sort_clause)
</pre>

I tested these codes with both SQLite3 and MySQL. And it works well.

thanks.

**Comment by zouchaoqun** [comment]
Thanks. I have just commited the change and it would be released in next minor version.
