### ISSUE TITLE
There's no faq icon found in the activity page

### ISSUE THREAD

**Issue by haru** [zouchaoqun/ezfaq#3]
Hi.

I found another problem.
There is no faq icon found in activity page when Redmine's root url is not '/'.

ex.

<pre>
mongrel_rails -start -e production --prefix /redmine
</pre>

Because following line in EzfaqLayoutHook does not work when root is not '/'.

<pre>
'<style type="text/css">dt.faqs { background-image: url(/plugin_assets/ezfaq_plugin/images/question.png); }</style>'
</pre>

Change code to

<pre>
baseurl = url_for(:controller => 'ezfaq', :action => 'index')
'<style type="text/css">dt.faqs { background-image: url(' + baseurl + '/../plugin_assets/ezfaq_plugin/images/question.png); }</style>'
</pre>

Then it will works.

**Comment by zouchaoqun** [comment]
hi haru
Do you try this?

add this at the end of config/environment.rb:

ActionController::AbstractRequest.relative_url_root = "/redmine"

**Comment by zouchaoqun** [comment]
no feedback for a long time. so close

**Comment by haru** [comment]
I'm sorry to no response. The problem was solved because of your answer. Thanks.
