### ISSUE TITLE
Displaying FAQ entries

### ISSUE THREAD

**Issue by unexist** [zouchaoqun/ezfaq#5]
Opening FAQ entries in via link is sometimes disturbing. I would like to have the entries directly after it's headline on the FAQ page without actually leaving the page. 

Before hacking your code myself - what do you think about this?

**Comment by zouchaoqun** [comment]
Do you mean add a quick view link in the faq-list page? It may be convenient somtimes, but it is not the common behavior of redmine(see issues).
So I would rather to keep ezfaq looks as same as redmine does.

**Comment by unexist** [comment]
Hm and displaying the FAQ as toc and scroll down for the answers? It's just annoying if you want to read all FAQs and have to switch through multiple windows or make heavily use of browser next/back stuff.

Are FAQs sorted by difficulty? (Btw: There is a typo in the localization: It's Difficulty and not Difficluty like you can see here: http://unexist.scrapping.cc/ezfaq/show/subtle?faq_id=2)

**Comment by zouchaoqun** [comment]
ezFAQ is designed to be a collaboration tool for faq collect and edit, so it looks like the issue section of redmine.
If it has all faq's and faq contents displayed in one page, I'm afraid it would mass the index page.
And if users want to have a full faq-list with answers, they can use the export to pdf function in the index page to get the list.
So I don't want to add every faq's content to the index page now.

FAQs are not sorted by difficulty. They are sorted by question under category group.

Thanks for pointing out the typo, it will be commited soon.

**Comment by zouchaoqun** [comment]
close
